# Generated by Django 6.1 on 2026-08-30 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('capacidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Estádio',
                'verbose_name_plural': 'Estádios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('temporada', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-temporada', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'temporada'), name='unique_campeonato_temporada')],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('escudo', models.ImageField(upload_to='escudos/')),
                ('ano_fundacao', models.IntegerField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='times_como_tecnico', to='campeonatos.pessoa')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('gols_mandante', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='campeonatos.campeonato')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='campeonatos.estadio')),
                ('time_mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_como_mandante', to='campeonatos.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_como_visitante', to='campeonatos.time')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['campeonato', 'rodada', 'data', 'horario'],
                'constraints': [models.UniqueConstraint(fields=('data', 'horario', 'estadio'), name='unique_partida_estadio_horario'), models.UniqueConstraint(fields=('campeonato', 'time_mandante', 'time_visitante'), name='unique_confronto_mando_campeonato')],
            },
        ),
        migrations.CreateModel(
            name='JogadorTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=50)),
                ('numero_camisa', models.PositiveIntegerField()),
                ('temporada', models.IntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times_como_jogador', to='campeonatos.pessoa')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_time', to='campeonatos.time')),
            ],
            options={
                'verbose_name': 'Jogador no Time',
                'verbose_name_plural': 'Jogadores nos Times',
                'ordering': ['time', 'numero_camisa'],
                'constraints': [models.UniqueConstraint(fields=('jogador', 'temporada'), name='unique_jogador_temporada'), models.UniqueConstraint(fields=('time', 'numero_camisa', 'temporada'), name='unique_camisa_time_temporada')],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='campeonatos.campeonato')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='campeonatos.time')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['campeonato', 'time'],
                'constraints': [models.UniqueConstraint(fields=('campeonato', 'time'), name='unique_time_por_campeonato')],
            },
        ),
    ]
